spring:
  application:
    name: fate

  datasource:
    initialization-mode: always
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: root
    password: root
    driverClassName: org.postgresql.Driver
    platform: postgresql

  jpa:
    properties:
      hibernate:
        default_schema: fate
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL91Dialect
    show-sql: true

mongodb:
  connection: mongodb://root:root@mongodbhostname:27017
  database: fate

server:
  port: 8080
  servlet:
    context-path: /fate

springdoc:
  packagesToScan: br.com.zumbolovsky.fateapp