spring:
  application:
    name: fate

  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    driverClassName: org.postgresql.Driver
    platform: postgresql

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL91Dialect
    show-sql: true
    open-in-view: false

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/db.changelog-master.yml

  mvc:
    async:
      request-timeout: 5000

  mustache:
    check-template-location: false

  cache:
    type: redis

  redis:
    host: localhost
    port: 6379

mongodb:
  connection: mongodb://root:root@localhost:27017
  database: fate

server:
  port: 8080
  servlet:
    context-path: /fate

springdoc:
  packagesToScan: br.com.zumbolovsky.fateapp