spring:
  application:
    name: fate

  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    driverClassName: org.postgresql.Driver
    platform: postgresql

  jpa:
    properties:
      hibernate:
        default_schema: fate
    generate-ddl: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL91Dialect
    show-sql: true

  mvc:
    async:
      request-timeout: 5000

mongodb:
  connection: mongodb://root:root@localhost:27017
  database: fate

server:
  port: 8080
  servlet:
    context-path: /fate

springdoc:
  packagesToScan: br.com.zumbolovsky.fateapp