spring:
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://172.23.0.3:5432/fate
    username: root
    password: root
    driverClassName: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
    database-platform: org.hibernate.dialect.PostgreSQL91Dialect
    show-sql: true

server:
  port: 8080
  servlet:
    context-path: /fate
