name: CI (TEST)

on:
  pull_request:
  push:
    branches:
      - main
      - feature/complete-java

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Configuring Maven permission
        run: chmod +x mvnw

      - name: Maven Test
        run: ./mvnw clean verify

      - name: Test Report
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: SpringBoot Report               # Name of the folder
          path: target/site/serenity/           # Path to test results