name: CI

permissions:
  # Read the baseline artifact in order to perform
  # the AppMap comparison.
  actions: read

  # Commit the AppMap configuration.
  # If the EndBug/add-and-commit is removed,
  # this can be changed to 'read'.
  contents: write

  # Add check annotations to the source code when
  # a problem is detected.
  checks: write

  # Add a comment to the pull request.
  pull-requests: write

on:
  pull_request:
  push:
    branches:
      - main
      - feature/complete-java
  schedule:
    - cron: '0 0 * * 0'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Checkout pull request head so that a commit can be made
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configuring Maven permission
        run: chmod +x mvnw

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      # Begin install-action snippet
      #
      - name: Install AppMap tools
        id: install-appmap
        uses: getappmap/install-action@v1
        with:
          project-type: maven
          build-patch-file: false
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
      #
      # End install-action snippet

      - name: Maven Test
        run: ./mvnw test

      - name: Archive AppMaps
        uses: getappmap/archive-action@v1
        with:
          revision: ${{ github.event.pull_request.base.sha }}